namespace AnonymizationService.EntityFrameworkCore;

public abstract class AnonymizationServiceEntityFrameworkCoreTestBase : AnonymizationServiceTestBase<AnonymizationServiceEntityFrameworkCoreTestModule>
{

}
