using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace AnonymizationService.Services.DbUri
{

	public class DbUriPatientData
	{
		public Patient patient { get; set; }
		public List<Event> events { get; set; }
		public Fup fup { get; set; }
	}
	public class Patient
	{
		public long id { get; set; }
		public long dateOfBirth { get; set; }
		public string sex { get; set; }
		public string municipality { get; set; }
		public int? exitusState { get; set; }
		public string exitusDate { get; set; }
		public int? exitusCause { get; set; }
		public string exitusCauseSpecific { get; set; }
		public string exitusCauseConcurrent { get; set; }
		public int? exitusSurvivalTimeProstate { get; set; }
		public int? exitusSurvivalTimeKidney { get; set; }
		public int? exitusSurvivalTimeTransitionals { get; set; }
		public int? exitusSurvivalTimeBladder { get; set; }
		public int? exitusSurvivalTimeBladderNMI { get; set; }
	}
	// FOLLOW UP 40
	public class Fup
	{
		public long id { get; set; }
		public long? idStructure { get; set; }
		// ESAMI 43
		public double? examEmCreatininemia06 { get; set; }
		public string examEmCreatininemia06Um { get; set; }
		public string examEmCreatininemia06Range { get; set; }
		public double? examEmCreatininemia12 { get; set; }
		public string examEmCreatininemia12Um { get; set; }
		public string examEmCreatininemia12Range { get; set; }
		public double? examEmCreatininemia24 { get; set; }
		public string examEmCreatininemia24Um { get; set; }
		public string examEmCreatininemia24Range { get; set; }
		public double? examEmCreatininemia36 { get; set; }
		public string examEmCreatininemia36Um { get; set; }
		public string examEmCreatininemia36Range { get; set; }
		public double? examEmCreatininemia48 { get; set; }
		public string examEmCreatininemia48Um { get; set; }
		public string examEmCreatininemia48Range { get; set; }
		public double? examEmCreatininemia60 { get; set; }
		public string examEmCreatininemia60Um { get; set; }
		public string examEmCreatininemia60Range { get; set; }
		public double? examEmCreatininemia72 { get; set; }
		public string examEmCreatininemia72Um { get; set; }
		public string examEmCreatininemia72Range { get; set; }
		public double? examEmCreatininemia84 { get; set; }
		public string examEmCreatininemia84Um { get; set; }
		public string examEmCreatininemia84Range { get; set; }
		public double? examEmCreatininemia96 { get; set; }
		public string examEmCreatininemia96Um { get; set; }
		public string examEmCreatininemia96Range { get; set; }
		public double? examEmCreatininemia108 { get; set; }
		public string examEmCreatininemia108Um { get; set; }
		public string examEmCreatininemia108Range { get; set; }
		public double? examEmCreatininemia120 { get; set; }
		public string examEmCreatininemia120Um { get; set; }
		public string examEmCreatininemia120Range { get; set; }
		public double? examEmGFR12 { get; set; }
		public string patientEnrolledProtocol { get; set; }
		public int? hasCardiovascularEvent { get; set; }
		public int? cardiovascularEventSurvival { get; set; }
		public int? hasPrimaryTumor { get; set; }
		public int? primaryTumorTimeTo { get; set; }
		public int? hasKidneyPrimaryTumor { get; set; }
		public int? kidneyPrimaryTumorTimeTo { get; set; }
		public int? hasRelapse { get; set; }
		public int? relapseSurvival { get; set; }
		public int? hasTherapyAdjuvant { get; set; }
		public int? hasDiabetes { get; set; }
		public int? diabetesTimeTo { get; set; }
		public List<Item> items { get; set; }
	}	
	public class Item
	{
		public long id { get; set; }
		public long? idStructure { get; set; }
		public bool? wcFlag { get; set; }
		public DateTime? fupDate { get; set; }
		public int? globalSurvival { get; set; }
		public int? deathCauseProgressioneNpl { get; set; }
		public string deathCauseOther { get; set; }
		public int? status { get; set; }
		public bool? tcTorace { get; set; }
		public string tcToraceData { get; set; }
		public bool? tcAddome { get; set; }
		public string tcAddomeData { get; set; }
		public bool? ecoAddome { get; set; }
		public string ecoAddomeData { get; set; }
		public bool? rxTorace { get; set; }
		public string rxToraceData { get; set; }
		public bool? scintiOssea { get; set; }
		public string scintiOsseaData { get; set; }
		public int? tpAnticoagulante { get; set; }
		public int? tpAntiaggregante { get; set; }
		public int? antiipertensivi { get; set; }
		public int? antiaritmici { get; set; }
		public int? psicofarmaci { get; set; }
		public int? ipercolesteromizzanti { get; set; }
		public int? antiH2InibitorePompa { get; set; }
		public int? pacemaker { get; set; }
		public int? litio { get; set; }
		public int? antianginosi { get; set; }
		public int? diuretici { get; set; }
		public int? alfaLitici { get; set; }
		public string altro { get; set; }
		public int? hypertensionTeraphyCalcioAntagonisti { get; set; }
		public int? hypertensionTherapyBetaBloccanti { get; set; }
		public int? hypertensionTeraphyDiuretici { get; set; }
		public int? hypertensionTeraphyRasInibitori { get; set; }
		public int? insorgenzaDiabete { get; set; }
		public int? diabeteI { get; set; }
		public int? diabeteII { get; set; }
		public int? timeToInsorgenzaDiabete { get; set; }
		public int? terapiaDiabeteIpoglicemizzanti { get; set; }
		public int? terapiaDiabeteInsulina { get; set; }
		public double? examEmCreatininemia { get; set; }
		public string examEmCreatininemiaUm { get; set; }
		public string examEmCreatininemiaRange { get; set; }
		public DateTime? dataUltimaCrea { get; set; }
		public int? timeToUltimaCrea { get; set; }
		public double? examEmGFR { get; set; }
		public double? examEmEmoglobina { get; set; }
		public string examEmEmoglobinaUm { get; set; }
		public string examEmEmoglobinaRange { get; set; }
		public double? examEmFosfatasiAlcalina { get; set; }
		public string examEmFosfatasiAlcalinaUm { get; set; }
		public string examEmFosfatasiAlcalinaRange { get; set; }
		public double? examEmCalcio { get; set; }
		public string examEmCalcioUm { get; set; }
		public string examEmCalcioRange { get; set; }
		public double? examEmLDH { get; set; }
		public string examEmLDHUm { get; set; }
		public string examEmLDHRange { get; set; }
		public double? examEmPiastrine { get; set; }
		public string examEmPiastrineUm { get; set; }
		public string examEmPiastrineRange { get; set; }
		public double? examEmGlicemia { get; set; }
		public string examEmGlicemiaUm { get; set; }
		public string examEmGlicemiaRange { get; set; }
		public double? trigliceridi { get; set; }
		public string trigliceridiUm { get; set; }
		public string trigliceridiRange { get; set; }
		public double? colesteroloTotale { get; set; }
		public string colesteroloTotUm { get; set; }
		public string colesteroloTotRange { get; set; }
		public double? gfr { get; set; }
		public bool? gfrRenalSequentialScintigraphy { get; set; }
		public int? gfrRenalSequentialScintigraphyType { get; set; }
		public bool? gfrIoexolo { get; set; }
		public int? gfrIoexoloType { get; set; }
		public string gfrOther { get; set; }
		public string gfrDate { get; set; }
		public int? gfrTimeTo { get; set; }
		public double? examUrAlbuminuria { get; set; }
		public string examUrAlbuminuriaUm { get; set; }
		public string examUrAlbuminuriaRange { get; set; }
		public double? examUrGlicosuria { get; set; }
		public string examUrGlicosuriaUm { get; set; }
		public string examUrGlicosuriaRange { get; set; }
		public double? examUrProteinuria24h12Mesi { get; set; }
		public string examUrProteinuria24h12MesiUm { get; set; }
		public string examUrProteinuria24h12MesiRange { get; set; }
		public double? examUrProteinuria24h { get; set; }
		public string examUrProteinuria24hUm { get; set; }
		public string examUrProteinuria24hRange { get; set; }
		public string examUrDataUltimaProteinuria24h { get; set; }
		public int? examUrProteinuria24hTimeTo { get; set; }
		public int? examUrMicroematuria { get; set; }
		public int? examUrMacroematuria { get; set; }
		public double? diametroMaggioreReneOperato { get; set; }
		public double? diametroMaggioreReneSano { get; set; }
		public int? ps { get; set; }
		public double? peso { get; set; }
		public int? therapyAdjuvant { get; set; }
		public bool? therapyAdjuvantTypeGammaKnife { get; set; }
		public bool? therapyAdjuvantTypeTerapiaMedica { get; set; }
		public bool? therapyAdjuvantTypeRadiofrequenza { get; set; }
		public bool? therapyAdjuvantTypeChemioterapia { get; set; }
		public bool? therapyAdjuvantTypeRadioterapia { get; set; }
		public string therapyAdjuvantGammaKnifeDate { get; set; }
		public double? therapyAdjuvantGammaKnifeDimension { get; set; }
		public string therapyAdjuvantGammaKnifePlacement { get; set; }
		public string therapyAdjuvantChemioterapiaDateStart { get; set; }
		public string therapyAdjuvantChemioterapiaDateEnd { get; set; }
		public string therapyAdjuvantChemioterapiaDose { get; set; }
		public string therapyAdjuvantRadiofrequenzaDate { get; set; }
		public double? therapyAdjuvantRadiofrequenzaDimension { get; set; }
		public string therapyAdjuvantRadiofrequenzaPlacement { get; set; }
		public string therapyAdjuvantRadioterapiaDate { get; set; }
		public double? therapyAdjuvantRadioterapiaDimension { get; set; }
		public string therapyAdjuvantRadioterapiaPlacement { get; set; }
		public string therapyAdjuvantTerapiaMedicaDateStart { get; set; }
		public string therapyAdjuvantTerapiaMedicaType { get; set; }
		public string therapyAdjuvantTerapiaMedicaDose { get; set; }
		public string therapyAdjuvantTerapiaMedicaResponse { get; set; }
		public int? therapyAdjuvantTerapiaMedicaCyclesNumber { get; set; }
		public int? therapyAdjuvantTerapiaMedicaDoseDec { get; set; }
		public string therapyAdjuvantTerapiaMedicaToxicity { get; set; }
		public string therapyAdjuvantTerapiaMedicaDateEnd { get; set; }
		public string image1 { get; set; }
		public string image2 { get; set; }
		public string image3 { get; set; }
		public Progress progress { get; set; }
		public Renalrecurrence renalRecurrence { get; set; }
		public Newkidneyprimarytumor newKidneyPrimaryTumor { get; set; }
		public Newprimarytumor newPrimaryTumor { get; set; }
		public Cardiovascularevent cardiovascularEvent { get; set; }
		public string wcProblem1Type { get; set; }
		public string wcProblem1Doctor { get; set; }
		public string wcProblem1Period { get; set; }
		public string wcProblem1Note { get; set; }
		public string wcProblem2Type { get; set; }
		public string wcProblem2Doctor { get; set; }
		public string wcProblem2Period { get; set; }
		public string wcProblem2Note { get; set; }
		public string wcDrug1Type { get; set; }
		public string wcDrug1Doctor { get; set; }
		public string wcDrug1Problem { get; set; }
		public string wcDrug1Note { get; set; }
		public string wcDrug2Type { get; set; }
		public string wcDrug2Doctor { get; set; }
		public string wcDrug2Problem { get; set; }
		public string wcDrug2Note { get; set; }
		public string wcExamEmNote { get; set; }
		public string wcHealthStatus { get; set; }
		public string insorgenzaDiabeteData { get; set; }
		public bool? rmn { get; set; }
		public double? hdl { get; set; }
		public string hdlrange { get; set; }
		public string ldlum { get; set; }
		public string ldlrange { get; set; }
		public string hdlum { get; set; }
		public double? ldl { get; set; }
		public int? immaginePresente { get; set; }
		public string rmndata { get; set; }
		public int? SSRI { get; set; }
	}
	public class Progress
	{
		public long id { get; set; }
		public long? idStructure { get; set; }
		public int? progressSurvival { get; set; }
		public int? progressMetastasis { get; set; }
		public string progressMetastasisDate { get; set; }
		public int? progressMetastasisFegato { get; set; }
		public int? progressMetastasisFegatoType { get; set; }
		public int? progressMetastasisOsso { get; set; }
		public int? progressMetastasisOssoType { get; set; }
		public int? progressMetastasisPolmone { get; set; }
		public int? progressMetastasisPolmoneType { get; set; }
		public int? progressMetastasisEncefalo { get; set; }
		public int? progressMetastasisEncefaloType { get; set; }
		public int? progressMetastasisTromboCavale { get; set; }
		public int? progressMetastasisTromboCavaleType { get; set; }
		public int? progressMetastasisLoggiaRenaleControl { get; set; }
		public int? progressMetastasisLoggiaRenaleControlType { get; set; }
		public int? progressMetastasisLinfonodi { get; set; }
		public int? progressMetastasisLinfonodiType { get; set; }
		public int? progressMetastasisPancreas { get; set; }
		public int? progressMetastasisPancreasType { get; set; }
		public int? progressMetastasisReneControlat { get; set; }
		public int? progressMetastasisReneControlatType { get; set; }
		public int? progressMetastasisSurrene { get; set; }
		public int? progressMetastasisSurreneType { get; set; }
		public int? progressMetastasisCute { get; set; }
		public int? progressMetastasisCuteType { get; set; }
		public int? progressMetastasisPeritoneo { get; set; }
		public int? progressMetastasisPeritoneoType { get; set; }
		public int? progressMetastasisColon { get; set; }
		public int? progressMetastasisColonType { get; set; }
		public int? progressMetastasisUretere { get; set; }
		public int? progressMetastasisUretereType { get; set; }
		public int? progressMetastasisOvaio { get; set; }
		public int? progressMetastasisOvaioType { get; set; }
		public int? progressMetastasisAltro { get; set; }
		public int? progressMetastasisMultiple { get; set; }
		public string progressMetastasisPostOpRevised { get; set; }
		public string progressMetastasisMultipleRevised { get; set; }
		public int? progressRescueTherapy { get; set; }
		public int? progressRescueResecabile { get; set; }
		public bool? progressRescueResezioneCompleta { get; set; }
		public string progressRescueTherapyResezioneCompletaNote { get; set; }
		public bool? progressRescueTherapyResezioneParziale { get; set; }
		public string progressRescueTherapyResezioneParzialeNote { get; set; }
		public bool? progressRescueTherapyRadiofrequenza { get; set; }
		public bool? progressRescueTherapyInterferone { get; set; }
		public bool? progressRescueTherapyAntiangiogenetici { get; set; }
		public bool? progressRescueTherapyChemioterapia { get; set; }
		public bool? progressRescueTherapyRT { get; set; }
		public bool? progressRescueTherapyGammaKnife { get; set; }
		public string progressRescueTherapyChemioterapiaDose { get; set; }
		public string progressRescueTherapyChemioterapiaDateStart { get; set; }
		public string progressRescueTherapyChemioterapiaDateEnd { get; set; }
		public string progressRescueTherapyRadioterapiaDate { get; set; }
		public double? progressRescueTherapyRadioterapiaDimension { get; set; }
		public string progressRescueTherapyRadioterapiaPlacement { get; set; }
		public string progressRescueTherapyRadiofrequenzaDate { get; set; }
		public double? progressRescueTherapyRadiofrequenzaDimension { get; set; }
		public string progressRescueTherapyRadiofrequenzaPlacement { get; set; }
		public string progressRescueTherapyGammaKnifeDate { get; set; }
		public double? progressRescueTherapyGammaKnifeDimension { get; set; }
		public string progressRescueTherapyGammaKnifePlacement { get; set; }
		public string progressRescueTherapyTerapiaMedicaDateStart { get; set; }
		public string progressRescueTherapyTerapiaMedicaDateEnd { get; set; }
		public string progressRescueTherapyTerapiaMedicaDose { get; set; }
		public int? progressRescueTherapyTerapiaMedicaCyclesNumber { get; set; }
		public int? progressRescueTherapyTerapiaMedicaDoseDec { get; set; }
		public string progressRescueTherapyTerapiaMedicaResponse { get; set; }
		public string progressRescueTherapyTerapiaMedicaType { get; set; }
		public string progressRescueTherapyTerapiaMedicaToxicity { get; set; }
	}
	public class Renalrecurrence
	{
		public long id { get; set; }
		public long? idStructure { get; set; }
		public int? relapseSurvival { get; set; }
		public string relapseDate { get; set; }
		public int? relapse { get; set; }
		public double? relapseDiameter { get; set; }
		public bool? typeRelapseAdrenal { get; set; }
		public bool? typeRelapseTranciaSezione { get; set; }
		public bool? typeRelapseinlodgerenal { get; set; }
		public bool? typeRelapseLynphonode { get; set; }
		public int? relapseRemoval { get; set; }
		public int? relapseTherapyRescue { get; set; }
		public int? relapseTherapyRescueType { get; set; }
	}
	public class Newkidneyprimarytumor
	{
		public long id { get; set; }
		public long? idStructure { get; set; }
		public int? nuovoTumorePrimarioRenale { get; set; }
		public string nuovoTumorePrimarioRenaleDate { get; set; }
		public int? nuovoTumorePrimarioRenaleSurvival { get; set; }
	}	
	public class Newprimarytumor
	{
		public long id { get; set; }
		public long? idStructure { get; set; }
		public int? newPrimaryTumor { get; set; }
		public string newPrimaryTumorDate { get; set; }
		public int? newPrimaryTumorPlacement { get; set; }
		public int? newPrimaryTumorPlacementOther { get; set; }
		public string timeToNuovoTumorePrimario { get; set; }
	}
	public class Cardiovascularevent
	{
		public long id { get; set; }
		public long? idStructure { get; set; }
		public int? cardiovascularEvent { get; set; }
		public int? cardiovascularEventKindCoronaropatia { get; set; }
		public int? cardiovascularEventKindCardiomiopatia { get; set; }
		public int? cardiovascularEventKindVasculopatia { get; set; }
		public int? cardiovascularEventKindIpertensione { get; set; }
		public int? cardiovascularEventKindInfarto { get; set; }
		public int? cardiovascularEventKindAritmie { get; set; }
		public int? cardiovascularEventKindMalattiaCerebrovascolare { get; set; }
		public int? cardiovascularEventKindAltro { get; set; }
		public int? cardiovascularEventIPAPeggiormentoNuovaInsorgenza { get; set; }
		public string cardiovascularEventDate { get; set; }
		public int? cardiovascularEventSurvival { get; set; }
		public string cardiovascularEventNote { get; set; }
	}
	public class Event
	{
		public Generalinfo generalInfo { get; set; }
		public Medicalhistory medicalHistory { get; set; }
		public Histological histological { get; set; }
		public Hospitalstay hospitalStay { get; set; }
		public Quest quest { get; set; }
		public Surgery surgery { get; set; }
		public Tac tac { get; set; }
	}
	public class Generalinfo
	{
		public long id { get; set; }
		public long? idStructure { get; set; }
		public DateTime examinationDate { get; set; }
	}
	// ANAMNESI 3
	public class Medicalhistory
	{
		public long id { get; set; }
		public long? idStructure { get; set; }
		public long? idKidney { get; set; }
		//Anamnnesi 3
		public DateTime? diagnosisDate { get; set; }
		public DateTime? hospitalizationDate { get; set; }
		public string medicalRecords { get; set; }
		public string oncologicalRecords { get; set; }
		public int? previousAbdominalOperations { get; set; }
		public int? patientSmoke { get; set; }
		public int? patientSmokeKind { get; set; }
		public string patientSmokeKindText { get; set; }
		public string patientSmokedYears { get; set; }
		public string patientSmokedYearsSince { get; set; }
		public string patientSmokeGG { get; set; }
		public string professionalCategory { get; set; }
		public bool? moduliOK { get; set; }
		// PS - ASA - COMORBIDITA' - BMI 4
		public int? preformanceStatus { get; set; }
		public int? asa { get; set; }
		public int? patientWeight { get; set; }
		public int? patientHeight { get; set; }
		public double? patientBMI { get; set; }

		public int? hyperTension { get; set; }
		public int? hypertensionTherapy { get; set; }
		public int? hypertensionTherapyCalcioAntagonisti { get; set; }
		public int? hypertensionTherapyBetaBloccanti { get; set; }
		public int? hypertensionTherapyDiuretici { get; set; }
		public int? hypertensionTherapyRasInibitori { get; set; }
		public int? hypertensionGoodControl { get; set; }

		public int? vonHippeLindau { get; set; }

		public int? karnofskyStatus { get; set; }
		public bool? karnofskyStatusA { get; set; }
		public bool? karnofskyStatusB { get; set; }
		public bool? karnofskyStatusC { get; set; }
		public string karnofskyStatusLevel { get; set; }

		public int? allergieAFarmaci { get; set; }
		public int? tpAnticoagulante { get; set; }
		public int? tpAntiaggregante { get; set; }
		public int? antiipertensivi { get; set; }
		public int? antiaritmici { get; set; }
		public int? psicofarmaci { get; set; }
		public int? antiH2InibitorePompa { get; set; }
		public int? ssri { get; set; }
		public int? pacemaker { get; set; }
		public int? litio { get; set; }
		public int? antianginosi { get; set; }
		public int? diuretici { get; set; }
		public int? alfaLitici { get; set; }
		public string altro { get; set; }
		public int? terapiaDiabeteIpoglicemizzanti { get; set; }
		public int? terapiaDiabeteInsulina { get; set; }
		public int? diabeteBuonControllo { get; set; }

		public bool? charlsonIndexComorbiditiesNessunaComorbidita { get; set; }
		public bool? charlsonIndexComorbiditiesInfartoMiocardicoAcuto { get; set; }
		public int? ima { get; set; }
		public int? cad { get; set; }
		public int? bpAc { get; set; }
		public int? ptca { get; set; }
		public bool? charlsonIndexComorbiditiesVasculopatiaPeriferica { get; set; }
		public int? bpPeripheral { get; set; }
		public int? ptcaPeripheral { get; set; }
		public int? aaa { get; set; }
		public int? aat { get; set; }
		public bool? charlsonIndexComorbiditiesMalattiaEpatica { get; set; }
		public int? hepatitisA { get; set; }
		public int? hepatitisB { get; set; }
		public int? hepatitisC { get; set; }
		public bool? charlsonIndexComorbiditiesDiabete { get; set; }
		public int? dmi { get; set; }
		public int? dmii { get; set; }
		public bool? charlsonIndexComorbiditiesScompensoCardiacoCongestizio { get; set; }
		public bool? charlsonIndexComorbiditiesMalattiaCerebrovascolare { get; set; }
		public bool? charlsonIndexComorbiditiesDemenza { get; set; }
		public bool? charlsonIndexComorbiditiesMalattiaPolmonare { get; set; }
		public bool? charlsonIndexComorbiditiesMalattiaDelTessutoConnettivo { get; set; }
		public bool? charlsonIndexComorbiditiesUlceraPeptica { get; set; }
		public bool? charlsonIndexComorbiditiesComplicanzeDelDiabete { get; set; }
		public bool? charlsonIndexComorbiditiesParaplegia { get; set; }
		public bool? charlsonIndexComorbiditiesNefropatia { get; set; }
		public bool? charlsonIndexComorbiditiesTumore { get; set; }
		public bool? charlsonIndexComorbiditiesLeucemia { get; set; }
		public bool? charlsonIndexComorbiditiesLinfoma { get; set; }
		public bool? charlsonIndexComorbiditiesTumoreMetastatico { get; set; }
		public bool? charlsonIndexComorbiditiesEpatopatiaSevera { get; set; }
		public bool? charlsonIndexComorbiditiesHIV { get; set; }
		public int? age { get; set; }
		public int? charlsonIndex { get; set; }
		public int? cciAge { get; set; }
		public string note { get; set; }

		// SINTOMATOLOGIA 5
		public int? symptomsBeginning { get; set; }
		public bool? symptomsBeginningLocalMacroematuria { get; set; }
		public bool? symptomsBeginningLocalColicaRenaleDoloreFianco { get; set; }
		public bool? symptomsBeginningLocalDoloriAddominali { get; set; }
		public bool? symptomsBeginningLocalVaricocele { get; set; }
		public bool? symptomsBeginningLocalMassaPalpabile { get; set; }
		public bool? symptomsBeginningLocalMicroematuria { get; set; }
		public bool? symptomsBeginningGeneralEdemiDeclivi { get; set; }
		public bool? symptomsBeginningGeneralIperpiressia { get; set; }
		public bool? symptomsBeginningGeneralAnemizzazione { get; set; }
		public bool? symptomsBeginningGeneralInsufficienzaAtriale { get; set; }
		public bool? symptomsBeginningGeneralCaloPonderale { get; set; }
		public bool? symptomsBeginningGeneralTosse { get; set; }
		public bool? symptomsBeginningGeneralSudorazioneNotturna { get; set; }
		public bool? symptomsBeginningGeneralAstenia { get; set; }
		public bool? symptomsBeginningGeneralIpertensione { get; set; }
		public bool? symptomsBeginningGeneralIpercalcemia { get; set; }
		public bool? symptomsBeginningGeneralAltro { get; set; }
		public bool? symptomsBeginningMetastasesDoloreOsseo { get; set; }
		public bool? symptomsBeginningMetastasesFratturaPatologica { get; set; }
		public bool? symptomsBeginningMetastasesDispnea { get; set; }
		public bool? symptomsBeginningMetastasesCefalea { get; set; }
		public bool? symptomsBeginningMetastasesAlterazioneVisus { get; set; }
		public bool? symptomsBeginningMetastasesEpilessia { get; set; }
		public bool? symptomsBeginningMetastasesAltro { get; set; }
		public bool? symptomsBeginningParaneoplasticVES { get; set; }
		public bool? symptomsBeginningParaneoplasticCachessia { get; set; }
		public bool? symptomsBeginningParaneoplasticAlterazioneFunzEpatica { get; set; }
		public bool? symptomsBeginningParaneoplasticPolicitemia { get; set; }
		public bool? symptomsBeginningParaneoplasticNeuromiopatie { get; set; }
		public bool? symptomsBeginningParaneoplasticAmiloidosi { get; set; }
		public bool? symptomsBeginningParaneoplasticAltro { get; set; }
		public string symptomsBeginningScore { get; set; }
		public string symptomsBeginningScoreString { get; set; }

		public int? symptomsAccompanying { get; set; }
		public bool? symptomsAccompanyingLocalMacroematuria { get; set; }
		public bool? symptomsAccompanyingLocalColicaRenaleDoloreFianco { get; set; }
		public bool? symptomsAccompanyingLocalDoloriAddominali { get; set; }
		public bool? symptomsAccompanyingLocalVaricocele { get; set; }
		public bool? symptomsAccompanyingLocalMassaPalpabile { get; set; }
		public bool? symptomsAccompanyingLocalMicroematuria { get; set; }
		public bool? symptomsAccompanyingGeneralEdemiDeclivi { get; set; }
		public bool? symptomsAccompanyingGeneralIperpiressia { get; set; }
		public bool? symptomsAccompanyingGeneralAnemizzazione { get; set; }
		public bool? symptomsAccompanyingGeneralInsufficienzaAtriale { get; set; }
		public bool? symptomsAccompanyingGeneralCaloPonderale { get; set; }
		public bool? symptomsAccompanyingGeneralTosse { get; set; }
		public bool? symptomsAccompanyingGeneralSudorazioneNotturna { get; set; }
		public bool? symptomsAccompanyingGeneralAstenia { get; set; }
		public bool? symptomsAccompanyingGeneralIpertensione { get; set; }
		public bool? symptomsAccompanyingGeneralIpercalcemia { get; set; }
		public bool? symptomsAccompanyingGeneralAltro { get; set; }
		public bool? symptomsAccompanyingMetastasesDoloreOsseo { get; set; }
		public bool? symptomsAccompanyingMetastasesFratturaPatologica { get; set; }
		public bool? symptomsAccompanyingMetastasesDispnea { get; set; }
		public bool? symptomsAccompanyingMetastasesCefalea { get; set; }
		public bool? symptomsAccompanyingMetastasesAlterazioneVisus { get; set; }
		public bool? symptomsAccompanyingMetastasesEpilessia { get; set; }
		public bool? symptomsAccompanyingMetastasesAltro { get; set; }
		public bool? symptomsAccompanyingParaneoplasticVES { get; set; }
		public bool? symptomsAccompanyingParaneoplasticCachessia { get; set; }
		public bool? symptomsAccompanyingParaneoplasticAlterazioneFunzEpatica { get; set; }
		public bool? symptomsAccompanyingParaneoplasticPolicitemia { get; set; }
		public bool? symptomsAccompanyingParaneoplasticNeuromiopatie { get; set; }
		public bool? symptomsAccompanyingParaneoplasticAmiloidosi { get; set; }
		public bool? symptomsAccompanyingParaneoplasticAltro { get; set; }
		public string symptomsAccompanyingScore { get; set; }
		public string symptomsAccompanyingScoreString { get; set; }
		// 2 TUMORE 6
		public int? secondTumor { get; set; }
		public string secondTumorDiagnosisDate { get; set; }
		public bool? secondTumorPlaceCute { get; set; }
		public bool? secondTumorPlaceOsso { get; set; }
		public bool? secondTumorPlaceProstata { get; set; }
		public bool? secondTumorPlaceVescica { get; set; }
		public bool? secondTumorPlaceColon { get; set; }
		public bool? secondTumorPlaceMammella { get; set; }
		public bool? secondTumorPlacePolmone { get; set; }
		public bool? secondTumorPlaceRene { get; set; }
		public bool? secondTumorPlaceFegato { get; set; }
		public bool? secondTumorPlaceLinfoprolifrativo { get; set; }
		public bool? secondTumorPlaceOvaio { get; set; }
		public bool? secondTumorPlaceUtero { get; set; }
		public bool? secondTumorPlaceEncefalo { get; set; }
		public bool? secondTumorPlaceEsofago { get; set; }
		public bool? secondTumorPlaceFaringe { get; set; }
		public bool? secondTumorPlaceLma { get; set; }
		public bool? secondTumorPlaceLmc { get; set; }
		public bool? secondTumorPlaceMieloma { get; set; }
		public bool? secondTumorPlaceStomaco { get; set; }
		public bool? secondTumorPlacePancreas { get; set; }
		public bool? secondTumorPlaceParacervicale { get; set; }
		public bool? secondTumorPlaceTumoreGlomico { get; set; }
		public string secondTumorPlaceAltro { get; set; }
		//TUMORE PRIMARIO 6
		public int? kidneyType { get; set; }
		public int? kidneyInjuriesNumberTot { get; set; }
		public int? kidneyInjuriesNumberTotFromExcel { get; set; }
		public int? kidneyInjuriesNumberDx { get; set; }
		public bool? kidneyNeoplasiaPlaceDxSuperiore { get; set; }
		public bool? kidneyNeoplasiaPlaceDxMedia { get; set; }
		public bool? kidneyNeoplasiaPlaceDxIlare { get; set; }
		public bool? kidneyNeoplasiaPlaceDxInferiore { get; set; }
		public bool? kidneyNeoplasiaPlaceDxCompleta { get; set; }
		public double? kidneyNeoplasiaDimensionDx { get; set; }
		public int? kidneyClinicalStage2009Dx { get; set; }
		public int? kidneyAdrenalInvolvementDx { get; set; }
		public int? kidneySavpDx { get; set; }
		public double? kidneyDxDiametroMaggiore { get; set; }
		public int? kidney1InjuriesNumber1 { get; set; }
		public bool? kidney1NeoplasiaPlace1Superiore { get; set; }
		public bool? kidney1NeoplasiaPlace1Media { get; set; }
		public bool? kidney1NeoplasiaPlace1Ilare { get; set; }
		public bool? kidney1NeoplasiaPlace1Inferiore { get; set; }
		public bool? kidney1NeoplasiaPlace1Completa { get; set; }
		public double? kidney1NeoplasiaDimension1 { get; set; }
		public int? kidney1ClinicalStage2009 { get; set; }
		public int? kidney1AdrenalInvolvement1 { get; set; }
		public int? kidney1Savp1 { get; set; }
		public double? kidney1DiametroMaggiore { get; set; }
		public int? kidneyInjuriesNumberSx { get; set; }
		public bool? kidneyNeoplasiaPlaceSxSuperiore { get; set; }
		public bool? kidneyNeoplasiaPlaceSxMedia { get; set; }
		public bool? kidneyNeoplasiaPlaceSxIlare { get; set; }
		public bool? kidneyNeoplasiaPlaceSxInferiore { get; set; }
		public bool? kidneyNeoplasiaPlaceSxCompleta { get; set; }
		public double? kidneyNeoplasiaDimensionSx { get; set; }
		public int? kidneyClinicalStage2009Sx { get; set; }
		public int? kidneySxAdrenalInvolvementSx { get; set; }
		public int? kidneySavpSx { get; set; }
		public double? kidneySxDiametroMaggiore { get; set; }
		public int? kidney2InjuriesNumber2 { get; set; }
		public bool? kidney2NeoplasiaPlace2Superiore { get; set; }
		public bool? kidney2NeoplasiaPlace2Media { get; set; }
		public bool? kidney2NeoplasiaPlace2Ilare { get; set; }
		public bool? kidney2NeoplasiaPlace2Inferiore { get; set; }
		public bool? kidney2NeoplasiaPlace2Completa { get; set; }
		public double? kidney2NeoplasiaDimension2 { get; set; }
		public int? kidney2ClinicalStage2009 { get; set; }
		public int? kidneyAdrenalInvolvement2 { get; set; }
		public int? kidney2Savp2 { get; set; }
		public double? kidney2DiametroMaggiore { get; set; }
		public int? kidneyClinicalStage2002 { get; set; }
		public int? kidneyContralateral { get; set; }
		// CISTE COMPLESSA 7
		public int? kidneyMonorene { get; set; }
		public int? kidneyInjuriesComplexCystNumberTot { get; set; }
		public int? kidneyInjuriesComplexCystNumberTotFromExcel { get; set; }
		public int? kidneyCCType { get; set; }
		public int? kidneyCCInjuriesNumberDx { get; set; }
		public bool? kidneyCCNeoplasiaPlaceDxSuperiore { get; set; }
		public bool? kidneyCCNeoplasiaPlaceDxMedia { get; set; }
		public bool? kidneyCCNeoplasiaPlaceDxIlare { get; set; }
		public bool? kidneyCCNeoplasiaPlaceDxInferiore { get; set; }
		public bool? kidneyCCNeoplasiaPlaceDxCompleta { get; set; }
		public double? kidneyCCNeoplasiaDimensionDx { get; set; }
		public int? kidney1CCInjuriesNumber1 { get; set; }
		public bool? kidney1CCNeoplasiaPlace1Superiore { get; set; }
		public bool? kidney1CCNeoplasiaPlace1Media { get; set; }
		public bool? kidney1CCNeoplasiaPlace1Ilare { get; set; }
		public bool? kidney1CCNeoplasiaPlace1Inferiore { get; set; }
		public bool? kidney1CCNeoplasiaPlace1Completa { get; set; }
		public double? kidney1CCNeoplasiaDimension1 { get; set; }
		public int? kidneyCCInjuriesNumberSx { get; set; }
		public bool? kidneyCCNeoplasiaPlaceSxSuperiore { get; set; }
		public bool? kidneyCCNeoplasiaPlaceSxMedia { get; set; }
		public bool? kidneyCCNeoplasiaPlaceSxIlare { get; set; }
		public bool? kidneyCCNeoplasiaPlaceSxInferiore { get; set; }
		public bool? kidneyCCNeoplasiaPlaceSxCompleta { get; set; }
		public double? kidneyCCNeoplasiaDimensionSx { get; set; }
		public int? kidney2CCInjuriesNumber2 { get; set; }
		public bool? kidney2CCNeoplasiaPlace2Superiore { get; set; }
		public bool? kidney2CCNeoplasiaPlace2Media { get; set; }
		public bool? kidney2CCNeoplasiaPlace2Ilare { get; set; }
		public bool? kidney2CCNeoplasiaPlace2Inferiore { get; set; }
		public bool? kidney2CCNeoplasiaPlace2Completa { get; set; }
		public double? kidney2CCNeoplasiaDimension2 { get; set; }
		public int? kidneyBosniakType { get; set; }
		// METASTASI 7
		public int? metastasis { get; set; }
		public int? metastasisMultiple { get; set; }
		public int? metastasisFegato { get; set; }
		public int? metastasisFegatoType { get; set; }
		public int? metastasisFegatoNumber { get; set; }
		public double? metastasisFegatoDimension { get; set; }
		public int? metastasisOsso { get; set; }
		public int? metastasisOssoType { get; set; }
		public int? metastasisOssoNumber { get; set; }
		public double? metastasisOssoDimension { get; set; }
		public int? metastasisPolmone { get; set; }
		public int? metastasisPolmoneType { get; set; }
		public int? metastasisPolmoneNumber { get; set; }
		public double? metastasisPolmoneDimension { get; set; }
		public int? metastasisEncefalo { get; set; }
		public int? metastasisEncefaloType { get; set; }
		public int? metastasisEncefaloNumber { get; set; }
		public double? metastasisEncefaloDimension { get; set; }
		public int? metastasisSurrene { get; set; }
		public int? metastasisSurreneType { get; set; }
		public int? metastasisSurreneNumber { get; set; }
		public double? metastasisSurreneDimension { get; set; }
		public int? metastasisCute { get; set; }
		public int? metastasisCuteType { get; set; }
		public int? metastasisCuteNumber { get; set; }
		public double? metastasisCuteDimension { get; set; }
		public int? metastasisPeritoneo { get; set; }
		public int? metastasisPeritoneoType { get; set; }
		public int? metastasisPeritoneoNumber { get; set; }
		public double? metastasisPeritoneoDimension { get; set; }
		public int? metastasisColon { get; set; }
		public int? metastasisColonType { get; set; }
		public int? metastasisColonNumber { get; set; }
		public double? metastasisColonDimension { get; set; }
		public int? metastasisUretere { get; set; }
		public int? metastasisUretereType { get; set; }
		public int? metastasisUretereNumber { get; set; }
		public double? metastasisUretereDimension { get; set; }
		public int? metastasisOvaio { get; set; }
		public int? metastasisOvaioType { get; set; }
		public int? metastasisOvaioNumber { get; set; }
		public double? metastasisOvaioDimension { get; set; }
		public int? metastasisAltro { get; set; }
		public string metastasisMultiplePlace { get; set; }
		public string metastasisMultipleInOnePlace { get; set; }
		public string metastasisOther { get; set; }
		public string metastasisNotes { get; set; }
		// ???
		public int? therapyNeoadjuvant { get; set; }
		public string therapyNeoadjuvantType { get; set; }
		public string therapyNeoadjuvantDateStart { get; set; }
		public double? therapyNeoadjuvantDose { get; set; }
		public int? therapyNeoadjuvantCiclesNumber { get; set; }
		public int? therapyNeoadjuvantDoseDec { get; set; }
		public string therapyNeoadjuvantSideEffects { get; set; }
		public string therapyNeoadjuvantResponse { get; set; }
		public string therapyNeoadjuvantDateEnd { get; set; }
		//LINFO ADENOPATIE 8
		public int? lymphadenopathy { get; set; }
		public bool? lymphadenopathyInteraortocavaleLocation { get; set; }
		public bool? lymphadenopathyParaorticoLocation { get; set; }
		public string lymphadenopathyAltroLocation { get; set; }
		public int? lymphadenopathySide { get; set; }
		public int? lymphnodesNumber { get; set; }
		public double? lymphnodesDimension { get; set; }
		public string lymphadenopathyNotes { get; set; }
		// TROMBO 8
		public int? thrombusNeoplastic { get; set; }
		public int? thrombusNeoplasticGrade { get; set; }
		public int? thrombusNeoplasticMobility { get; set; }
		public string thrombusNeoplasticExtension { get; set; }
		public int? thrombusCranialLimitUnder { get; set; }
		public int? thrombusCranialLimitOver { get; set; }
		// ESAMI STRUMENTALI 8
		public int? examToolEchoColorDoppler { get; set; }
		public int? examToolEchocardiogram { get; set; }
		public int? examToolEchoabdomen { get; set; }
		public int? examToolTACBrain { get; set; }
		public int? examToolCavografia { get; set; }
		public int? examToolTACAngio { get; set; }
		public int? examToolTACAbdominal { get; set; }
		public int? examToolRMN { get; set; }
		public int? examToolTACThoracic { get; set; }
		public int? examToolEchoendoscopy { get; set; }
		public int? examToolCavalFilter { get; set; }
		public int? examToolEchocardio { get; set; }
		public int? examToolChestRx { get; set; }
		public int? examToolScintigraphy { get; set; }
		public int? examToolTargetedRx { get; set; }
		public double? examToolGfr { get; set; }
		public bool? examToolGfrRenalSequentialScintigraphy { get; set; }
		public int? examToolGfrRenalSequentialScintigraphyType { get; set; }
		public bool? examToolGfrIoexolo { get; set; }
		public int? examToolGfrIoexoloType { get; set; }
		public string examToolGfrOther { get; set; }
		// ESAMI EMATOCHMICI PRE OPERATORI 9
		public string examEmDate { get; set; }
		public double? examEmEmoglobina { get; set; }
		public string examEmEmoglobinaUm { get; set; }
		public string examEmEmoglobinaRange { get; set; }
		public double? examEmFosfatasiAlcalina { get; set; }
		public string examEmFosfatasiAlcalinaUm { get; set; }
		public string examEmFosfatasiAlcalinaRange { get; set; }
		public double? examEmCreatininemia { get; set; }
		public string examEmCreatininemiaUm { get; set; }
		public string examEmCreatininemiaRange { get; set; }
		public double? examEmeGFR { get; set; }
		public double? examEmPiastrine { get; set; }
		public string examEmPiastrineUm { get; set; }
		public string examEmPiastrineRange { get; set; }
		public double? examEmClearance { get; set; }
		public string examEmClearanceUm { get; set; }
		public string examEmClearanceRange { get; set; }
		public double? examEmCalcio { get; set; }
		public string examEmCalcioUm { get; set; }
		public string examEmCalcioRange { get; set; }
		public double? examEmVES { get; set; }
		public string examEmVESUm { get; set; }
		public string examEmVESRange { get; set; }
		public double? examEmLDH { get; set; }
		public string examEmLDHUm { get; set; }
		public string examEmLDHRange { get; set; }
		public double? examEmAlbumina { get; set; }
		public string examEmAlbuminaUm { get; set; }
		public double? examEmNeutrofili { get; set; }
		public string examEmNeutrofiliUm { get; set; }
		public string examEmNeutrofiliRange { get; set; }
		public double? examEmLinfociti { get; set; }
		public string examEmLinfocitiUm { get; set; }
		public string examEmLinfocitiRange { get; set; }
		public double? examEmMonociti { get; set; }
		public string examEmMonocitiUm { get; set; }
		public string examEmMonocitiRange { get; set; }
		public double? examEmEosinofili { get; set; }
		public string examEmEosinofiliUm { get; set; }
		public string examEmEosinofiliRange { get; set; }
		public double? examEmBasofili { get; set; }
		public string examEmBasofiliUm { get; set; }
		public string examEmBasofiliRange { get; set; }
		public double? examEmColesteroloTot { get; set; }
		public string examEmColesteroloTotUm { get; set; }
		public string examEmColesteroloTotRange { get; set; }
		public double? examEmHdl { get; set; }
		public string examEmHdlUm { get; set; }
		public string examEmHdlRange { get; set; }
		public double? examEmLdl { get; set; }
		public string examEmLdlUm { get; set; }
		public string examEmLdlRange { get; set; }
		public int? examEmIpercolesterolemia { get; set; }
		public int? examEmIpercolesterolemiaStatina { get; set; }
		public double? examEmGlicemia { get; set; }
		public string examEmGlicemiaUm { get; set; }
		public string examEmGlicemiaRange { get; set; }
		// EAMI URINe PrE OperATORI 10 
		public double? examUrAlbuminuria { get; set; }
		public string examUrAlbuminuriaUm { get; set; }
		public string examUrAlbuminuriaRange { get; set; }
		public double? examUrGlicosuria { get; set; }
		public string examUrGlicosuriaUm { get; set; }
		public string examUrGlicosuriaRange { get; set; }
		public double? examUrProteinuria24h { get; set; }
		public string examUrProteinuria24hUm { get; set; }
		public string examUrProteinuria24hRange { get; set; }
		// SCORE mRCC 10 
		public int? mskccKarnofskyPerformanceStatus { get; set; }
		public int? mskccTimeFromDiagnosisToTreatment { get; set; }
		public int? mskccConcentrationLdh { get; set; }
		public int? mskccLowerHemoglobinLevel { get; set; }
		public int? mskccCalciumLevel { get; set; }
		public int? mskccRiskGroup { get; set; }
		public int? imdcKarnofskyPerformanceStatus { get; set; }
		public int? imdcTimeFromDiagnosisToTreatment { get; set; }
		public int? imdcConcentrationLdh { get; set; }
		public int? imdcLowerHemoglobinLevel { get; set; }
		public int? imdcCalciumLevel { get; set; }
		public int? imdcUlnPlateletsCounts { get; set; }
		public int? imdcAncGreaterThanUln { get; set; }
		public int? imdcRiskGroup { get; set; }
		public int? ccfTimeFromDiagnosisToTreatment { get; set; }
		public int? ccfConcentrationLdh { get; set; }
		public int? ccfLowerHemoglobinLevel { get; set; }
		public int? ccfCalciumLevel { get; set; }
		public int? ccfRadiotherapyBeforeSurgery { get; set; }
		public int? ccfPresenceOfHepaticMetastases { get; set; }
		public int?cfRiskGroup { get; set; }
		// INTEint? PRECEDENTI 11
		public int? ipa { get; set; }
		public int? hypercholesterolemia { get; set; }
		public int? hypertriglyceridemia { get; set; }
		public int? atvTurpHolep { get; set; }
		public int? rrp { get; set; }
		public int? tonsillectomy { get; set; }
		public int? adenoidectomy { get; set; }
		public int? hernioplastyUnilateral { get; set; }
		public int? hernioplastyBilateral { get; set; }
		public int? rplnd { get; set; }
		public int? varicocelectomy { get; set; }
		public int? saphenectomyUnilateral { get; set; }
		public int? saphenectomyBilateral { get; set; }
		public int? sm { get; set; }
		public int? neurologicalDiseases { get; set; }
		public int? otherMst { get; set; }
		public int? hypothyroidism { get; set; }
		public int? hyperthyroidism { get; set; }
		public int? geneticDiseases { get; set; }
		public string geneticDiseasesDescr { get; set; }
		public int? allergies { get; set; }
		public string allergiesDescr { get; set; }
		public string otherDiseases { get; set; }
		public string other { get; set; }
		// 13
		public int? alcohol { get; set; }
		public int? alcoholQuantity { get; set; }
		public int? physicalActivity { get; set; }
		public int? anticonceptionalPill { get; set; }
		public int? menopause { get; set; }
		public int? hormonalTherapy { get; set; }
		// 9
		public string trigliceridiUm { get; set; }
		public double? trigliceridi { get; set; }
		public string trigliceridiRange { get; set; }
		public int? ipocolesterolemizzanti { get; set; }
		// 11
		public double? ejectionFraction { get; set; }
		public int? efdysfunctionLevel { get; set; }
		public int? anxietyDepressiveDisorder { get; set; }
		public int? anxiousPanicAttacksDisorder { get; set; }
		public int? depressiveDisorder { get; set; }
	}
	// REFERTO ISTOLOGICO 33
	public class Histological
	{
		//RENI 33
		public long id { get; set; }
		public long? idStructure { get; set; }
		public long? idKidney { get; set; }
		public string kidney1Side { get; set; }
		public int? kidney1HistologicalType { get; set; }
		public int? kidney1HistologicalTypeBenign { get; set; }
		public string kidney1HistologicalTypeBenignOther { get; set; }
		public int? kidney1Cryoablation { get; set; }
		public string kidney1CryoablationOther { get; set; }
		public int? kidney1HistologicalTypeMalignant { get; set; }
		public string kidney1HistologicalTypeMalignantOther { get; set; }
		public bool? kidney1HistologicalTypeMalignantSarcomatoid { get; set; }
		public double? kidney1ResectionMarginsDist { get; set; }
		public int? kidney1R0R1 { get; set; }
		public int? kidney1Multifocal { get; set; }
		public int? kidney1InjuriesNumber { get; set; }
		public double? kidney1TumorDimension { get; set; }
		public bool? kidney1Wilms { get; set; }
		public bool? kidney1PlaceSuperiore { get; set; }
		public bool? kidney1PlaceIlare { get; set; }
		public bool? kidney1PlaceCompleta { get; set; }
		public bool? kidney1PlaceMedia { get; set; }
		public bool? kidney1PlaceInferiore { get; set; }
		public int? kidney1ThrombusConsistency { get; set; }
		public int? kidney1FatInfiltration { get; set; }
		public bool? kidney1FatInfiltrationGrassoPerirenale { get; set; }
		public bool? kidney1FatInfiltrationGrassoSenoRenale { get; set; }
		public int? kidney1AdrenalInvolvement { get; set; }
		public int? kidney1AdrenalInvolvementType { get; set; }
		public int? kidney1Necrosis { get; set; }
		public double? necrosis1Perc { get; set; }
		public int? kidney1InvasionMicrovascular { get; set; }
		public int? kidney1ExcretoryWay { get; set; }
		public int? kidney1PathologicalStage2009 { get; set; }
		public int? kidney1PN2009 { get; set; }
		public int? kidney1M { get; set; }
		public int? kidney1Grading { get; set; }
		public int? kidney1IsupWho2016 { get; set; }
		public int? kidney1PathologicalStage { get; set; }
		public int? kidney1PN { get; set; }
		public string kidney2Side { get; set; }
		public int? kidney2HistologicalType { get; set; }
		public int? kidney2HistologicalTypeBenign { get; set; }
		public string kidney2HistologicalTypeBenignOther { get; set; }
		public int? kidney2Cryoablation { get; set; }
		public string kidney2CryoablationOther { get; set; }
		public int? kidney2HistologicalTypeMalignant { get; set; }
		public string kidney2HistologicalTypeMalignantOther { get; set; }
		public bool? kidney2HistologicalTypeMalignantSarcomatoid { get; set; }
		public double? kidney2ResectionMarginsDist { get; set; }
		public int? kidney2R0R1 { get; set; }
		public int? kidney2Multifocal { get; set; }
		public int? kidney2InjuriesNumber { get; set; }
		public double? kidney2TumorDimension { get; set; }
		public bool? kidney2Wilms { get; set; }
		public bool? kidney2PlaceSuperiore { get; set; }
		public bool? kidney2PlaceIlare { get; set; }
		public bool? kidney2PlaceCompleta { get; set; }
		public bool? kidney2TumorMedia { get; set; }
		public bool? kidney2PlaceInferiore { get; set; }
		public int? kidney2ThrombusConsistency { get; set; }
		public int? kidney2FatInfiltration { get; set; }
		public bool? kidney2FatInfiltrationGrassoPerirenale { get; set; }
		public bool? kidney2FatInfiltrationGrassoSenoRenale { get; set; }
		public int? kidney2AdrenalInvolvement { get; set; }
		public int? kidney2AdrenalInvolvementType { get; set; }
		public int? kidney2Necrosis { get; set; }
		public double? kidney2NecrosisPerc { get; set; }
		public int? kidney2InvasionMicrovascular { get; set; }
		public int? kidney2ExcretoryWay { get; set; }
		public int? kidney2PathologicalStage2009 { get; set; }
		public int? kidney2PN2009 { get; set; }
		public int? kidney2M { get; set; }
		public int? kidney2Grading { get; set; }
		public int? kidney2PathologicalStage { get; set; }
		public int? kidney2PN { get; set; }
		public int? bilateralNecrosis { get; set; }
		public string note { get; set; }
		// MAYO SCORING POINT 35
		public int? kidney1MayoPathologicalStage { get; set; }
		public int? kidney1MayoTumorDimension { get; set; }
		public int? kidney1MayoPN { get; set; }
		public int? kidney1MayoGrading { get; set; }
		public int? kidney1MayoNecrosis { get; set; }
		public int? kidney1MayoScore { get; set; }
		public string kidney1MayoRisk { get; set; }
		public int? kidney2MayoPathologicalStage { get; set; }
		public int? kidney2MayoTumorDimension { get; set; }
		public int? kidney2MayoPN { get; set; }
		public int? kidney2MayoGrading { get; set; }
		public int? kidney2MayoNecrosis { get; set; }
		public int? kidney2MayoScore { get; set; }
		public string kidney2MayoRisk { get; set; }
		// senza nome 35
		public int? venousInvasion { get; set; }
		public bool? venousInvasionVenaRenaleSx { get; set; }
		public bool? venousInvasionVenaRenaleDx { get; set; }
		public bool? venousInvasionVenaCava { get; set; }
		public bool? venousInvasionVenaAtrioDx { get; set; }
		public int? veinWallInfiltration { get; set; }
		public bool? veinWallInfiltrationVenaRenaleSx { get; set; }
		public bool? veinWallInfiltrationVenaRenaleDx { get; set; }
		public bool? veinWallInfiltrationVenaCava { get; set; }
		public int? lymphnodesPrecavalePos { get; set; }
		public int? lymphnodesPrecavaleNeg { get; set; }
		public int? lymphnodesRetrocavalePos { get; set; }
		public int? lymphnodesRetrocavaleNeg { get; set; }
		public int? lymphnodesInteraortocavalePos { get; set; }
		public int? lymphnodesInteraortocavaleNeg { get; set; }
		public int? lymphnodesParaorticoSxPos { get; set; }
		public int? lymphnodesParaorticoSxNeg { get; set; }
		public int? lymphnodesPeriIlariDxPos { get; set; }
		public int? lymphnodesPeriIlariDxNeg { get; set; }
		public int? lymphnodesPeriIlariSxPos { get; set; }
		public int? lymphnodesPeriIlariSxNeg { get; set; }
		public int? lymphnodesTotPos { get; set; }
		public int? lymphnodesTotNeg { get; set; }
		public int? lymphnodesTot { get; set; }
		public int? lymphnodesTotPosNoCalc { get; set; }
		public int? lymphnodesTotNegNoCalc { get; set; }
		//32
		public int? kidney2ISUPWHO2016 { get; set; }
	}
	// DEGENZA POST OPERATORIA 36
	public class Hospitalstay
	{
		public long id { get; set; }
		public long? idStructure { get; set; }
		public long? idKidney { get; set; }
		//DEGENZA POST OPERATORIA 36
		public string dischargeDate { get; set; }
		public int? hospitalStayDaysTot { get; set; }
		public int? hospitalStayDaysPostOp { get; set; }
		public int? transfusionsHomologous { get; set; }
		public int? transfusionsAutologous { get; set; }
		public int? transfusionsTot { get; set; }
		public int? transfusionsTotWithSurgery { get; set; }
		// ESAME EMATOCHIMICI PRIMA GIORNATA POST OPERATORIA 37
		public double? leucociti1aGiornata { get; set; }
		public string leucociti1aGiornataUm { get; set; }
		public string leucociti1aGiornataRange { get; set; }
		public double? emoglobina1aGiornata { get; set; }
		public string emoglobina1aGiornataUm { get; set; }
		public string emoglobina1aGiornataRange { get; set; }
		public double? ematocrito1aGiornata { get; set; }
		public string ematocrito1aGiornataUm { get; set; }
		public string ematocrito1aGiornataRange { get; set; }
		public double? piastrine1aGiornata { get; set; }
		public string piastrine1aGiornataUm { get; set; }
		public string piastrine1aGiornataRange { get; set; }
		public double? creatinina1aGiornata { get; set; }
		public string creatinina1aGiornataUm { get; set; }
		public string creatinina1aGiornataRange { get; set; }
		public double? calcio1aGiornata { get; set; }
		public string calcio1aGiornataUm { get; set; }
		public string calcio1aGiornataRange { get; set; }
		public double? neutrofili1aGiornata { get; set; }
		public string neutrofili1aGiornataUm { get; set; }
		public string neutrofili1aGiornataRange { get; set; }
		public double? linfociti1aGiornata { get; set; }
		public string linfociti1aGiornataUm { get; set; }
		public string linfociti1aGiornataRange { get; set; }
		public double? monociti1aGiornata { get; set; }
		public string monociti1aGiornataUm { get; set; }
		public string monociti1aGiornataRange { get; set; }
		public double? eosinofili1aGiornata { get; set; }
		public string eosinofili1aGiornataUm { get; set; }
		public string eosinofili1aGiornataRange { get; set; }
		public double? basofili1aGiornata { get; set; }
		public string basofili1aGiornataUm { get; set; }
		public string basofili1aGiornataRange { get; set; }
		public double? potassio1aGiornata { get; set; }
		public string potassio1aGiornataUm { get; set; }
		public string potassio1aGiornataRange { get; set; }
		public double? sodio1aGiornata { get; set; }
		public string sodio1aGiornataUm { get; set; }
		public string sodio1aGiornataRange { get; set; }
		public double? proteinuria24h1aGiornata { get; set; }
		public string proteinuria24h1aGiornataUm { get; set; }
		public string proteinuria24h1aGiornataRange { get; set; }
		public double? albuminuria1aGiornata { get; set; }
		public string albuminuria1aGiornataUm { get; set; }
		public string albuminuria1aGiornataRange { get; set; }
		// ESAMI EMATOCHIMICI POST OPERATORI 38
		public double? examEmEmoglobina { get; set; }
		public string examEmEmoglobinaUm { get; set; }
		public string examEmEmoglobinaRange { get; set; }
		public double? examEmCreatininemia { get; set; }
		public string examEmCreatininemiaUm { get; set; }
		public string examEmCreatininemiaRange { get; set; }
		public double? examEmGFR { get; set; }
		public double? examEmPiastrine { get; set; }
		public string examEmPiastrineUm { get; set; }
		public string examEmPiastrineRange { get; set; }
		public double? examEmClearance { get; set; }
		public string examEmClearanceUm { get; set; }
		public string examEmClearanceRange { get; set; }
		public double? examEmCalcio { get; set; }
		public string examEmCalcioUm { get; set; }
		public string examEmCalcioRange { get; set; }
		public double? examEmLDH { get; set; }
		public string examEmLDHUm { get; set; }
		public string examEmLDHRange { get; set; }
		public double? examEmNeutrofili { get; set; }
		public string examEmNeutrofiliUm { get; set; }
		public string examEmNeutrofiliRange { get; set; }
		public double? examEmLinfociti { get; set; }
		public string examEmLinfocitiUm { get; set; }
		public string examEmLinfocitiRange { get; set; }
		public double? examEmMonociti { get; set; }
		public string examEmMonocitiUm { get; set; }
		public string examEmMonocitiRange { get; set; }
		public double? examEmEosinofili { get; set; }
		public string examEmEosinofiliUm { get; set; }
		public string examEmEosinofiliRange { get; set; }
		public double? examEmBasofili { get; set; }
		public string examEmBasofiliUm { get; set; }
		public string examEmBasofiliRange { get; set; }
		public double? examEmAlbumina { get; set; }
		public string examEmAlbuminaUm { get; set; }
		public double? examEmColTot { get; set; }
		public string examEmColTotUm { get; set; }
		public string examEmColTotRange { get; set; }
		public double? examEmHdl { get; set; }
		public string examEmHdlUm { get; set; }
		public string examEmHdlRange { get; set; }
		public double? examEmLdl { get; set; }
		public string examEmLdlUm { get; set; }
		public string examEmLdlRange { get; set; }
		public int? examEmIpercol { get; set; }
		// COMPLICANZE POST OERATORIE 39
		public bool? complicationNessuna { get; set; }
		public bool? complicationAnemizzazione { get; set; }
		public bool? complicationFistola { get; set; }
		public bool? complicationPancreatite { get; set; }
		public bool? complicationShockSettico { get; set; }
		public bool? complicationInfezioneSuperficialeFerita { get; set; }
		public bool? complicationInfezioneProfondaFerita { get; set; }
		public bool? complicationSetticemia { get; set; }
		public bool? complicationEmatomaRetroperitoneale { get; set; }
		public bool? complicationOcclusioneIntestinale { get; set; }
		public bool? complicationLomboceleEDolorePostop { get; set; }
		public bool? complicationLaparocele { get; set; }
		public bool? complicationLinforragia { get; set; }
		public bool? complicationInsufficienzaRenale { get; set; }
		public bool? complicationInsufficienzaSurrenalica { get; set; }
		public bool? complicationComplicanzeTromboemboliche { get; set; }
		public bool? complicationEdemaPolmonare { get; set; }
		public bool? complicationExitus { get; set; }
		public string complicationOther { get; set; }
		public int? reexamination { get; set; }
		public string reexaminationDate { get; set; }
		public int? therapyAnalgesicTime { get; set; }
		public string therapyAnalgesicDrug { get; set; }
		public string therapyAnalgesicDose { get; set; }
		public int? iceballSize1DayPostOp { get; set; }
		public string note { get; set; }
		// CLAVIEN CLASSIFICATION 39
		public bool? clavienClassification0 { get; set; }
		public bool? clavienClassificationI { get; set; }
		public bool? clavienClassificationII { get; set; }
		public bool? clavienClassificationIII { get; set; }
		public bool? clavienClassificationIIIa { get; set; }
		public bool? clavienClassificationIIIb { get; set; }
		public bool? clavienClassificationIV { get; set; }
		public bool? clavienClassificationIVa { get; set; }
		public bool? clavienClassificationIVb { get; set; }
		public bool? clavienClassificationV { get; set; }
		public bool? clavienClassificationD { get; set; }
	}
	// QUIZ 15
	public class Quest
	{
		public long id { get; set; }
		public long? idStructure { get; set; }
		public long? idKidney { get; set; }
		public string questDate { get; set; }
		//16
		public int? iiefTot { get; set; }
		public int? iiefSumEF { get; set; }
		public int? iiefSumIS { get; set; }
		public int? iiefSumOF { get; set; }
		public int? iiefSumSD { get; set; }
		public int? iiefSumOS { get; set; }
		public int? iief01 { get; set; }
		public int? iief02 { get; set; }
		public int? iief03 { get; set; }
		public int? iief04 { get; set; }
		public int? iief05 { get; set; }
		public int? iief06 { get; set; }
		public int? iief07 { get; set; }
		public int? iief08 { get; set; }
		public int? iief09 { get; set; }
		public int? iief10 { get; set; }
		public int? iief11 { get; set; }
		public int? iief12 { get; set; }
		public int? iief13 { get; set; }
		public int? iief14 { get; set; }
		public int? iief15 { get; set; }
		// IPSS 18
		public int? ipss01 { get; set; }
		public int? ipss02 { get; set; }
		public int? ipss03 { get; set; }
		public int? ipss04 { get; set; }
		public int? ipss05 { get; set; }
		public int? ipss06 { get; set; }
		public int? ipss07 { get; set; }
		public int? ipssTot { get; set; }
		public int? ipssQol { get; set; }
		public int? ipssSumIrritative { get; set; }
		public int? ipssSumRetentive { get; set; }
		// BECK 20
		public bool? beck0101 { get; set; }
		public bool? beck0102 { get; set; }
		public bool? beck0103 { get; set; }
		public bool? beck0104 { get; set; }
		public bool? beck0201 { get; set; }
		public bool? beck0202 { get; set; }
		public bool? beck0203 { get; set; }
		public bool? beck0204 { get; set; }
		public bool? beck0301 { get; set; }
		public bool? beck0302 { get; set; }
		public bool? beck0303 { get; set; }
		public bool? beck0304 { get; set; }
		public bool? beck0401 { get; set; }
		public bool? beck0402 { get; set; }
		public bool? beck0403 { get; set; }
		public bool? beck0404 { get; set; }
		public bool? beck0501 { get; set; }
		public bool? beck0502 { get; set; }
		public bool? beck0503 { get; set; }
		public bool? beck0504 { get; set; }
		public bool? beck0601 { get; set; }
		public bool? beck0602 { get; set; }
		public bool? beck0603 { get; set; }
		public bool? beck0604 { get; set; }
		public bool? beck0701 { get; set; }
		public bool? beck0702 { get; set; }
		public bool? beck0703 { get; set; }
		public bool? beck0704 { get; set; }
		public bool? beck0801 { get; set; }
		public bool? beck0802 { get; set; }
		public bool? beck0803 { get; set; }
		public bool? beck0804 { get; set; }
		public bool? beck0901 { get; set; }
		public bool? beck0902 { get; set; }
		public bool? beck0903 { get; set; }
		public bool? beck0904 { get; set; }
		public bool? beck1001 { get; set; }
		public bool? beck1002 { get; set; }
		public bool? beck1003 { get; set; }
		public bool? beck1004 { get; set; }
		public bool? beck1101 { get; set; }
		public bool? beck1102 { get; set; }
		public bool? beck1103 { get; set; }
		public bool? beck1104 { get; set; }
		public bool? beck1201 { get; set; }
		public bool? beck1202 { get; set; }
		public bool? beck1203 { get; set; }
		public bool? beck1204 { get; set; }
		public bool? beck1301 { get; set; }
		public bool? beck1302 { get; set; }
		public bool? beck1303 { get; set; }
		public bool? beck1304 { get; set; }
		public bool? beck1401 { get; set; }
		public bool? beck1402 { get; set; }
		public bool? beck1403 { get; set; }
		public bool? beck1404 { get; set; }
		public bool? beck1501 { get; set; }
		public bool? beck1502 { get; set; }
		public bool? beck1503 { get; set; }
		public bool? beck1504 { get; set; }
		public bool? beck1601 { get; set; }
		public bool? beck1602 { get; set; }
		public bool? beck1603 { get; set; }
		public bool? beck1604 { get; set; }
		public bool? beck1701 { get; set; }
		public bool? beck1702 { get; set; }
		public bool? beck1703 { get; set; }
		public bool? beck1704 { get; set; }
		public bool? beck1801 { get; set; }
		public bool? beck1802 { get; set; }
		public bool? beck1803 { get; set; }
		public bool? beck1804 { get; set; }
		public bool? beck1901 { get; set; }
		public bool? beck1902 { get; set; }
		public bool? beck1903 { get; set; }
		public bool? beck1904 { get; set; }
		public bool? beck2001 { get; set; }
		public bool? beck2002 { get; set; }
		public bool? beck2003 { get; set; }
		public bool? beck2004 { get; set; }
		public bool? beck2101 { get; set; }
		public bool? beck2102 { get; set; }
		public bool? beck2103 { get; set; }
		public bool? beck2104 { get; set; }
		public int? beckTot { get; set; }
		// FSFI 23
		public int? fsfi01 { get; set; }
		public int? fsfi02 { get; set; }
		public int? fsfi03 { get; set; }
		public int? fsfi04 { get; set; }
		public int? fsfi05 { get; set; }
		public int? fsfi06 { get; set; }
		public int? fsfi07 { get; set; }
		public int? fsfi08 { get; set; }
		public int? fsfi09 { get; set; }
		public int? fsfi10 { get; set; }
		public int? fsfi11 { get; set; }
		public int? fsfi12 { get; set; }
		public int? fsfi13 { get; set; }
		public int? fsfi14 { get; set; }
		public int? fsfi15 { get; set; }
		public int? fsfi16 { get; set; }
		public int? fsfi17 { get; set; }
		public int? fsfi18 { get; set; }
		public int? fsfi19 { get; set; }
		public double? fsfiTotA { get; set; }
		public double? fsfiTotB { get; set; }
		public double? fsfiTotC { get; set; }
		public double? fsfiTotD { get; set; }
		public double? fsfiTotE { get; set; }
		public double? fsfiTotF { get; set; }
		// SF36 27
		public int? sf3601 { get; set; }
		public int? sf3602 { get; set; }
		public int? sf3603a { get; set; }
		public int? sf3603b { get; set; }
		public int? sf3603c { get; set; }
		public int? sf3603d { get; set; }
		public int? sf3603e { get; set; }
		public int? sf3603f { get; set; }
		public int? sf3603g { get; set; }
		public int? sf3603h { get; set; }
		public int? sf3603i { get; set; }
		public int? sf3603j { get; set; }
		public int? sf3604a { get; set; }
		public int? sf3604b { get; set; }
		public int? sf3604c { get; set; }
		public int? sf3604d { get; set; }
		public int? sf3605a { get; set; }
		public int? sf3605b { get; set; }
		public int? sf3605c { get; set; }
		public int? sf3606 { get; set; }
		public int? sf3607 { get; set; }
		public int? sf3608 { get; set; }
		public int? sf3609a { get; set; }
		public int? sf3609b { get; set; }
		public int? sf3609c { get; set; }
		public int? sf3609d { get; set; }
		public int? sf3609e { get; set; }
		public int? sf3609f { get; set; }
		public int? sf3609g { get; set; }
		public int? sf3609h { get; set; }
		public int? sf3609i { get; set; }
		public int? sf3610 { get; set; }
		public int? sf3611a { get; set; }
		public int? sf3611b { get; set; }
		public int? sf3611c { get; set; }
		public int? sf3611d { get; set; }
		public int? sf36q1 { get; set; }
		public int? sf36q2 { get; set; }
		public int? sf36q3 { get; set; }
		public int? sf36q4 { get; set; }
		public int? sf36q5 { get; set; }
		public int? sf36q6 { get; set; }
		public int? sf36q7 { get; set; }
		public int? sf36q8 { get; set; }
		public int? sf36qTotRF { get; set; }
		public int? sf36qTotRM { get; set; }
	}
	// INTERVENTO 30
	public class Surgery
	{
		// dati GENERALI 30
		public long id { get; set; }
		public long? idKidney { get; set; }
		public string examinationDate { get; set; }
		public int? examinationAge { get; set; }
		public long? idStructure { get; set; }
		public long? idDoctor { get; set; }
		public long? idHospital { get; set; }
		public int? examinationTime { get; set; }
		public string note { get; set; }
		// TIPOLOGIA INTERVENTO 30
		public int? pringleManeuver { get; set; }
		public int? pringleManeuverTime { get; set; }
		public int? embolization { get; set; }
		public int? conservativeTherapy { get; set; }
		public int? stentUreteralePreOp { get; set; }
		public int? incisionType { get; set; }
		public int? access { get; set; }
		public int? liverDerotation { get; set; }
		public int? riparazioneCalici { get; set; }
		// TECNint?RATORIA 30 
		public int? surgicalTechnique { get; set; }
		public int? surgicalTechniqueThermoablationMinutes { get; set; }
		public int? surgicalTechniqueThermoablationWatt { get; set; }
		public string surgicalTechniqueThermoablationNeedleType { get; set; }
		public string surgicalTechniqueThermoablationAblationType { get; set; }
		public int? agoCrioablazione { get; set; }
		public int? freezingDurationCicle1 { get; set; }
		public int? freezingDurationCicle2 { get; set; }
		// RENI 31
		public string kidney1Side { get; set; }
		public int? kidney1PlannedOperationType { get; set; }
		public int? kidney1OperationType { get; set; }
		public int? kidney1NephrectomyType { get; set; }
		public int? kidney1IschemiaType { get; set; }
		public int? kidney1IschemiaTime { get; set; }
		public string kidney1IschemiaParzialeTot { get; set; }
		public int? kidney1IceballSize { get; set; }
		public bool? kidney1HaemostasisTypeArgon { get; set; }
		public bool? kidney1HaemostasisTypeFloseal { get; set; }
		public bool? kidney1HaemostasisTypeGlubran { get; set; }
		public bool? kidney1HaemostasisTypeGrasso { get; set; }
		public bool? kidney1HaemostasisTypePunti { get; set; }
		public bool? kidney1HaemostasisTypePlaget { get; set; }
		public bool? kidney1HaemostasisTypeTabotamp { get; set; }
		public bool? kidney1HaemostasisTypeElettrocauterizzazione { get; set; }
		public bool? kidney1HaemostasisTypeAvitene { get; set; }
		public bool? kidney1HaemostasisTypeSurgiflo { get; set; }
		public bool? kidney1HaemostasisTypeTachosil { get; set; }
		public int? kidney1AdrenalectomyType { get; set; }
		public int? kidney1ThrombusConsistency { get; set; }
		public int? kidney1Savp { get; set; }
		public int? kidney1SibScoreSurface { get; set; }
		public int? kidney1SibScoreIntermediate { get; set; }
		public int? kidney1SibScoreBase { get; set; }
		public int? kidney1SibScoreSum { get; set; }
		public string kidney2Side { get; set; }
		public int? kidney2PlannedOperationType { get; set; }
		public int? kidney2OperationType { get; set; }
		public int? kidney2NephrectomyType { get; set; }
		public int? kidney2IschemiaType { get; set; }
		public int? kidney2IschemiaTime { get; set; }
		public string kidney2IschemiaParzialeTot { get; set; }
		public int? kidney2IceballSize { get; set; }
		public bool? kidney2HaemostasisTypeArgon { get; set; }
		public bool? kidney2HaemostasisTypeFloseal { get; set; }
		public bool? kidney2HaemostasisTypeGlubran { get; set; }
		public bool? kidney2HaemostasisTypeGrasso { get; set; }
		public bool? kidney2HaemostasisTypePunti { get; set; }
		public bool? kidney2HaemostasisTypePlaget { get; set; }
		public bool? kidney2HaemostasisTypeTabotamp { get; set; }
		public bool? kidney2HaemostasisTypeElettrocauterizzazione { get; set; }
		public bool? kidney2HaemostasisTypeAvitene { get; set; }
		public bool? kidney2HaemostasisTypeSurgiflo { get; set; }
		public bool? kidney2HaemostasisTypeTachosil { get; set; }
		public int? kidney2AdrenalectomyType { get; set; }
		public int? kidney2ThrombusConsistency { get; set; }
		public int? kidney2Savp { get; set; }
		public int? kidney2SibScoreSurface { get; set; }
		public int? kidney2SibScoreIntermediate { get; set; }
		public int? kidney2SibScoreBase { get; set; }
		public int? kidney2SibScoreSum { get; set; }
		// TROMBO 32
		public string kidney1ThrombusTimeOfClamping { get; set; }
		public string kidney2ThrombusTimeOfClamping { get; set; }
		public int? cranialLimitUnder { get; set; }
		public int? cranialLimitOver { get; set; }
		public int? cavotomia { get; set; }
		public bool? cavotomiaTypeSemplice { get; set; }
		public bool? cavotomiaTypeResezioneVenaCavaFocale { get; set; }
		public bool? cavotomiaTypeResezioneVenaCavaParziale { get; set; }
		public bool? cavotomiaTypeResezioneCavaCilindricaSegmentale { get; set; }
		public bool? cavotomiaTypeInnestoAutologo { get; set; }
		public bool? cavotomiaTypePacthGoretex { get; set; }
		public int? atriotomia { get; set; }
		public int? minithoracotomy { get; set; }
		public int? extracorporealCirculation { get; set; }
		public int? extracorporealCirculationTime { get; set; }
		public int? extracorporealCirculationShutdown { get; set; }
		public double? hypothermiaTemperature { get; set; }
		// senza titolo 32
		public int? bloodLoss { get; set; }
		public int? autologousTransfusions { get; set; }
		public int? transfusionsTot { get; set; }
		// TERAPIA METASTASI 32
		public int? metastasisTherapy { get; set; }
		public bool? metastasisTherapyTypeResezioneCompleta { get; set; }
		public string metastasisTherapyResezioneCompleta { get; set; }
		public bool? metastasisTherapyTypeResezioneParziale { get; set; }
		public string metastasisTherapyResezioneParziale { get; set; }
		public bool? metastasisTherapyTypeRadiofrequenza { get; set; }
		public bool? metastasisTherapyTypeRadioterapia { get; set; }
		public bool? metastasisTherapyTypeGammaKnife { get; set; }
		// COMPLICANZA 32
		public bool? complicationsNessuna { get; set; }
		public bool? complicationsPneumotorace { get; set; }
		public bool? complicationsLesioneDellaMilza { get; set; }
		public bool? complicationsSplenectomia { get; set; }
		public bool? complicationsLesioniEpatiche { get; set; }
		public bool? complicationsLesioniPancreatiche { get; set; }
		public bool? complicationsLesioniDuodenali { get; set; }
		public bool? complicationsLesioniIleoEColon { get; set; }
		public bool? complicationsLesioniSurrenaliche { get; set; }
		public bool? complicationsEmorraggia { get; set; }
		public bool? complicationsConversioneChirurgica { get; set; }
		public string complicationsOther { get; set; }
		// TIPOLOGIA INTERVENTO 30 
		public int? stentUreteralePreOpType { get; set; }
		// senza titolo 32
		public int? homologousTransfusions { get; set; }
	}
	// TAC visualizzazione immagine 12
	public class Tac
	{
		public long id { get; set; }
		public long? idStructure { get; set; }
		public long? idKidney { get; set; }
		public int? paduaScoreExophyticEndophyticRate { get; set; }
		public int? paduaScoreRenalRim { get; set; }
		public int? paduaScoreLocation { get; set; }
		public int? paduaScoreRenalSinus { get; set; }
		public int? paduaScoreUCS { get; set; }
		public int? paduaScoreSize { get; set; }
		public int? paduaScoreFace { get; set; }
		public string paduaScoreTot { get; set; }
		public string renalScoreR { get; set; }
		public int? renalScoreRVal { get; set; }
		public string renalScoreE { get; set; }
		public int? renalScoreEVal { get; set; }
		public string renalScoreN { get; set; }
		public int? renalScoreNVal { get; set; }
		public string renalScoreA { get; set; }
		public string renalScoreL { get; set; }
		public int? renalScoreLVal { get; set; }
		public string renalScoreTot { get; set; }
		public int? dapCancerDiameterTransversePlane { get; set; }
		public int? dapAxialDistance { get; set; }
		public int? dapPolarDistance { get; set; }
		public int? dapTotal { get; set; }
		public int? mapThicknessOfThePosteriorPerirenalFat { get; set; }
		public int? mapPerirenalStranding { get; set; }
		public int? mapscoreTotal { get; set; }
		public int? abcTumorsCategory { get; set; }
		public int? arterialSystemNumber { get; set; }
		public int? arterialSystemLocation { get; set; }
		public int? arterialSystemSide { get; set; }
		public string arterialSystemCancerRelationship { get; set; }
		public string arterialSystemAnatomicVariantsNotes { get; set; }
		public int? venousSystemNumber { get; set; }
		public int? venousSystemLocation { get; set; }
		public int? venousSystemSide { get; set; }
		public string venousSystemCancerRelationship { get; set; }
		public string venousSystemAnatomicVariantsNotes { get; set; }
		public int? urinaryTractNumber { get; set; }
		public int? urinaryTractLocation { get; set; }
		public int? urinaryTractSide { get; set; }
		public string urinaryTractCancerRelationship { get; set; }
		public string urinaryTractAnatomicVariantsNotes { get; set; }
		public double? tumorVolumeDx { get; set; }
		public double? endophyticTumorVolumeDx { get; set; }
		public double? volumeOfHealthyParenchymaDx { get; set; }
		public double? totalSurfaceAreaDx { get; set; }
		public double? contactSurfaceAreaDx { get; set; }
		public double? tumorVolumeSx { get; set; }
		public double? endophyticTumorVolumeSx { get; set; }
		public double? volumeOfHealthyParenchymaSx { get; set; }
		public double? totalSurfaceAreaSx { get; set; }
		public double? contactSurfaceAreaSx { get; set; }
		public int? dwi { get; set; }
		public double? signalT1 { get; set; }
		public double? signalT2 { get; set; }
		public int? enhancement { get; set; }
		public int? mayoRadiographicEvidenceOfHemorrage { get; set; }
		public int? mayoRadiographicEvidenceOfNecrosis { get; set; }
		public int? mayoRadiographicEvidenceOfCalcification { get; set; }
		public int? mayoRadiographicEvidenceOfNeovascularity { get; set; }
		public string image1 { get; set; }
		public string image2 { get; set; }
		public string image3 { get; set; }
		public int? immaginePresente { get; set; }
		// 13
		public double? cindexHDistanceCentralHilarAxisCancerCenter { get; set; }
		public double? cindexVDistanceCentralHilarAxisMaxDiamCenter { get; set; }
		public double? cindexCancerDiam { get; set; }
		public double? cindexHypotenuseTriangle { get; set; }
		public double? cindexCancerRadius { get; set; }
		public double? cindexCR { get; set; }
		public double? cindexTotal { get; set; }
	}
}
